spring:
  application:
    name:
      pets-backend

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-url: http://localhost:8082/realms/pets-backend
          jwk-set-uri: http://localhost:8082/realms/pets-backend/protocol/openid-connect/certs

  datasource:
    url: jdbc:postgresql://postgres:5432/pets-backend
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  management:
    endpoints:
      web:
        exposure:
          include:
            - "*"
    endpoint:
      prometheus:
        enabled: true

keycloak:
  server-url: http://localhost:8082
  realm: pets-backend
  client-id: pets-backend
  username: admin
  password: user!123

logging:
  level:
    org:
      keycloak: DEBUG
      jboss:
        resteasy: DEBUG
