services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    container_name: keycloak
    ports:
      - "8082:8082"
    command: start-dev
    volumes:
      - keycloak-data:/opt/keycloak/data
    env_file:
      - ./spring.env

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    env_file:
      - ./spring.env

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./spring.env

  emotipet-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emotipet-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - keycloak
    env_file:
      - ./spring.env

  nginx:
    image: nginx:latest
    depends_on:
      - emotipet-backend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  postgres-data:
  prometheus-data:
  grafana-data:
  keycloak-data: