services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    env_file:
      - ./spring.env

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./spring.env

  emotipet-backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NO_CACHE=true
    container_name: emotipet-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - ./spring.env
      
volumes:
  postgres-data:
  prometheus-data:
  grafana-data: