name: CI for pets-backend

on:
  push:
    branches:
      - main
      - develop
      - feat/ci
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: pets-backend/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('pets-backend/**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Run tests with Maven
      run: mvn clean verify -f pets-backend/pom.xml


